import { marked } from "marked";
import TurndownService from "turndown";
import { gfm } from "turndown-plugin-gfm";

const HEADER_LINE_RE = /^(\s{0,3}#{1,6})\s*(.*?)\s*$/;
const BULLET_LINE_RE = /^(\s*)([+*])\s+/;
const ORDERED_LIST_LINE_RE = /^(\s*)(\d+)([.)])\s+/;
const BLANK_LINE_STREAK_RE = /\n{3,}/g;
const CODE_FENCE_RE = /^\s*```/;

marked.setOptions({
  gfm: true,
  breaks: false,
});

const turndownService = new TurndownService({
  headingStyle: "atx",
  bulletListMarker: "-",
  codeBlockStyle: "fenced",
  emDelimiter: "*",
  strongDelimiter: "**",
});

turndownService.use(gfm);

export function renderMarkdownToEditorHtml(markdown: string): string {
  return marked.parse(markdown ?? "") as string;
}

function decodeHtmlEntities(text: string): string {
  if (!text) return "";

  if (typeof document !== "undefined") {
    const textarea = document.createElement("textarea");
    textarea.innerHTML = text;
    return textarea.value;
  }

  return text
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'");
}

function preserveHardbreakTrailingSpaces(line: string): string {
  const match = line.match(/^(.*?)(\s+)$/);
  if (!match) return line;

  const content = match[1];
  const trailingSpaces = match[2];
  if (!content || content.trim().length === 0) {
    return "";
  }

  return trailingSpaces.length >= 2 ? `${content}  ` : content;
}

function normalizeNonFenceLine(line: string): string {
  const trimmedForHardbreak = preserveHardbreakTrailingSpaces(
    decodeHtmlEntities(line).replace(/\u00a0/g, " ")
  );
  if (!trimmedForHardbreak) {
    return "";
  }

  const headerMatch = trimmedForHardbreak.match(HEADER_LINE_RE);
  if (headerMatch) {
    const [, headerMarks, headerText] = headerMatch;
    const trimmedHeader = headerText.trim();
    const suffix = trimmedForHardbreak.endsWith("  ") ? "  " : "";
    return trimmedHeader ? `${headerMarks} ${trimmedHeader}${suffix}` : `${headerMarks}${suffix}`;
  }

  const suffix = trimmedForHardbreak.endsWith("  ") ? "  " : "";
  const lineBody = suffix ? trimmedForHardbreak.slice(0, -2) : trimmedForHardbreak;
  const normalizedBody = lineBody
    .replace(BULLET_LINE_RE, "$1- ")
    .replace(ORDERED_LIST_LINE_RE, "$1$2$3 ");
  return `${normalizedBody}${suffix}`;
}

// Normalize the HTML generated by the editor to remove editor-specific markup and styles that would interfere with clean Markdown conversion.
export function normalizeEditorHtmlForMarkdown(html: string): string {
  if (typeof document === "undefined") {
    return html;
  }

  const container = document.createElement("div");
  container.innerHTML = html;

  // Tiptap table resize markup causes Turndown to emit raw HTML instead of GFM.
  container.querySelectorAll("colgroup, col").forEach((node) => node.remove());

  container.querySelectorAll("table, thead, tbody, tfoot, tr, th, td").forEach((node) => {
    node.removeAttribute("style");
  });

  container.querySelectorAll("th, td").forEach((cell) => {
    const elementChildren = Array.from(cell.children);
    if (
      elementChildren.length > 0 &&
      elementChildren.every((child) => child.tagName === "P")
    ) {
      cell.innerHTML = elementChildren.map((child) => child.innerHTML).join("<br>");
    }
  });

  return container.innerHTML;
}

// Convert HTML to Markdown without additional text normalization so the round-trip check
// can detect any formatting drift introduced by the editor pipeline.
export function htmlToEditorMarkdown(html: string): string {
  return turndownService.turndown(html ?? "");
}

export function normalizeMarkdownForEditor(markdown: string): string {
  const lines = (markdown ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split("\n");
  const normalized: string[] = [];
  let inFence = false;

  for (const line of lines) {
    if (CODE_FENCE_RE.test(line)) {
      inFence = !inFence;
      normalized.push(line);
      continue;
    }

    if (inFence) {
      normalized.push(line);
      continue;
    }

    normalized.push(normalizeNonFenceLine(line));
  }

  return normalized
    .join("\n")
    .replace(BLANK_LINE_STREAK_RE, "\n\n")
    .replace(/^\n+|\n+$/g, "");
}
