# Module purpose:
# Contains helpers for filtering and normalizing surrounding markdown blocks before
# they are sent to the VLM as contextual text for semantic table summaries.

from .constants import _MARKDOWN_COMMENT_RE, _MARKDOWN_IMAGE_LINE_RE


def _normalize_markdown_context_for_vlm(text: str) -> str:
    """Strip markdown comments and normalize whitespace before sending context to the VLM."""

    without_comments = _MARKDOWN_COMMENT_RE.sub(" ", text or "")
    return " ".join(without_comments.split())


def _is_text_like_context_block(block: str) -> bool:
    """
    Return True when a markdown block is useful as textual context.

    This intentionally excludes image-only/media scaffold blocks (including the synthetic
    table-image blocks inserted by the extractor) so the "after" context is actual prose/text.
    """

    # Remove HTML comments first (UUID markers, placeholders, debug markers).
    text = _MARKDOWN_COMMENT_RE.sub(" ", block or "")
    remaining_lines: list[str] = []

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        # Ignore markdown image embeds (plain or quoted).
        if _MARKDOWN_IMAGE_LINE_RE.match(line):
            continue

        # Ignore synthetic table-image/VLM summary scaffolding generated by this pipeline.
        if "Table (image)" in line:
            continue
        if "Table summary (VLM)" in line:
            continue

        # Ignore fallback/status-only scaffold messages tied to image export.
        if "Local image export failed" in line or "Local crop failed" in line:
            continue

        remaining_lines.append(line)

    normalized = " ".join(" ".join(remaining_lines).split())
    return any(ch.isalnum() for ch in normalized)
