"""Constants shared across Agent v2 nodes."""

SEARCH_TOP_K = 15
NON_STRONG_SIGNAL_FILE_TOP_K = 10
POTENTIAL_MATCH_PROMOTION_THRESHOLD = 0.70
SEMANTIC_FILE_FILTER_FALLBACK_K_STEPS = (50, 100, 200)
SEARCH_EXCLUSION_OVERFETCH_MULTIPLIERS = (1, 3, 6)

